### ISSUE TITLE
environment naming

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#70] opened 2019-12-09 12:50 UTC
Change from `--dev` and `--prod` by `--local` and `--containers`.

**Comment by fenekku** [comment] 2019-12-10 17:53
Haha I think this is the 2nd duplicate of #55 , the first one being #57 . Is it possible that one of those was meant to be renaming the commands? For example: `invenio-cli services ...` or something like we discussed in Chicago?

**Closed** 2019-12-12 10:41 UTC
